version: 2

jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          ADMIN_EMAIL: info@technovationchallenge.org
          AIRBRAKE_PROJECT_ID: n-a
          AIRBRAKE_PROJECT_KEY: n-a
          AIRBRAKE_RAILS_ENV: test
          AWS_BUCKET_NAME: technovation-attachments-test
          BING_MAPS_API_KEY: n-a
          CAMPAIGN_MONITOR_API_KEY: n-a
          CHAPTER_AMBASSADOR_LIST_ID: n-a
          CHAPTER_AMBASSADOR_SLACK_URL: n-a
          COOKIES_ADMIN_PERMISSION_TOKEN: admin_permission_token_JUNE_2018
          COOKIES_AUTH_TOKEN: auth_token_JUNE_2018
          COOKIES_GLOBAL_INVITATION_TOKEN: global_invitation_token_JUNE_2018
          COOKIES_IP_GEOLOCATION: ip_geolocation_JUNE_2018
          COOKIES_LAST_PROFILE_USED: last_profile_used_JUNE_2018
          COOKIES_LAST_VISITED_SUBMISSION_SECTION: last_visited_submission_section_JUNE_2018
          COOKIES_REDIRECTED_FROM: redirected_from_JUNE_2018
          COOKIES_SESSION_TOKEN: session_token_JUNE_2018
          COOKIES_SIGNUP_EMAIL: n-a
          COOKIES_SIGNUP_TOKEN: signup_token_JUNE_2018
          COOKIES_SIGNUP_WIZARD_MODE: signup_wizard_mode_SEPT_2018
          DATES_CERTIFICATES_AVAILABLE_DAY: 20
          DATES_CERTIFICATES_AVAILABLE_MONTH: 6
          DATES_CERTIFICATES_AVAILABLE_YEAR: 2020
          DATES_LIVE_QUARTERFINALS_ENDS_DAY: 20
          DATES_LIVE_QUARTERFINALS_ENDS_MONTH: 5
          DATES_LIVE_QUARTERFINALS_ENDS_YEAR: 2020
          DATES_MENTOR_TRAINING_DAY: 15
          DATES_MENTOR_TRAINING_MONTH: 10
          DATES_MENTOR_TRAINING_YEAR: 2018
          DATES_NEW_SEASON_START_DAY: 1
          DATES_NEW_SEASON_START_MONTH: 10
          DATES_OFFICIAL_START_OF_SEASON_DAY: 1
          DATES_OFFICIAL_START_OF_SEASON_MONTH: 10
          DATES_OFFICIAL_START_OF_SEASON_YEAR: 2020
          DATES_QUARTERFINALS_BEGINS_DAY: 27
          DATES_QUARTERFINALS_BEGINS_MONTH: 4
          DATES_QUARTERFINALS_BEGINS_YEAR: 2020
          DATES_QUARTERFINALS_ENDS_DAY: 20
          DATES_QUARTERFINALS_ENDS_MONTH: 5
          DATES_QUARTERFINALS_ENDS_YEAR: 2020
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_DAY: 1
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_MONTH: 4
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_YEAR: 2020
          DATES_REGIONAL_PITCH_EVENTS_ENDS_DAY: 1
          DATES_REGIONAL_PITCH_EVENTS_ENDS_MONTH: 5
          DATES_REGIONAL_PITCH_EVENTS_ENDS_YEAR: 2020
          DATES_REGISTRATION_OPENS_DAY: 1
          DATES_REGISTRATION_OPENS_MONTH: 10
          DATES_REGISTRATION_OPENS_YEAR: 2018
          DATES_RPE_OFFICIALITY_FINALIZED_DAY: 22
          DATES_RPE_OFFICIALITY_FINALIZED_MONTH: 4
          DATES_RPE_OFFICIALITY_FINALIZED_YEAR: 2020
          DATES_SEMIFINALS_BEGINS_DAY: 1
          DATES_SEMIFINALS_BEGINS_MONTH: 6
          DATES_SEMIFINALS_BEGINS_YEAR: 2020
          DATES_SEMIFINALS_ENDS_DAY: 17
          DATES_SEMIFINALS_ENDS_MONTH: 6
          DATES_SEMIFINALS_ENDS_YEAR: 2020
          DATES_SUBMISSION_DEADLINE_DAY: 13
          DATES_SUBMISSION_DEADLINE_MONTH: 4
          DATES_SUBMISSION_DEADLINE_YEAR: 2020
          DATES_TEAM_REGISTRATION_DEADLINE_DAY: 16
          DATES_TEAM_REGISTRATION_DEADLINE_MONTH: 3
          DATES_TEAM_REGISTRATION_DEADLINE_YEAR: 2020
          DATES_VIRTUAL_QUARTERFINALS_ENDS_DAY: 20
          DATES_VIRTUAL_QUARTERFINALS_ENDS_MONTH: 5
          DATES_VIRTUAL_QUARTERFINALS_ENDS_YEAR: 2020
          ENABLE_HOMEPAGE_BANNER: true
          FINALISTS_URL: "https://some/url"
          GOOGLE_ANALYTICS_ID: n-a
          GOOGLE_MAPS_API_KEY: n-a
          GOOGLE_PLACES_API_KEY: n-a
          GOOGLE_TIMEZONE_API_KEY: n-a
          HELP_EMAIL: help@technovationchallenge.org
          HOST_DOMAIN: localhost:3000
          JUDGE_LIST_ID: n-a
          JUDGE_SLACK_SIGNUP_URL: n-a
          JUDGE_TRAINING_URL: n-a
          MAILCHIMP_API_KEY: n-a
          MAILGUN_PRIVATE_KEY: n-a
          MENTOR_LIST_ID: n-a
          MENTOR_SLACK_SIGNUP_URL: n-a
          NEWSLETTER_URL: "https://some/other/url"
          NEW_RELIC_LICENSE_KEY: n-a
          PARENT_CONSENT_PDF: n-a
          PARENT_LIST_ID: n-a
          PDFTK_PATH: /usr/bin/pdftk
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          REDIS_URL: redis://127.0.0.1:6379/0
          STUDENT_LIST_ID: n-a
          THUNKABLE_PROMO_IMAGE: n-a
          WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
      - image: circleci/postgres:11-alpine-ram

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run: sudo apt-get update; sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x

      - run: sudo apt-get install pdftk

      - run:
          name: Install wkhtmltopdf
          command: |
            wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
            sudo apt install ./wkhtmltox_0.12.5-1.stretch_amd64.deb

      # Needed to polyfill canvas elements for testing in Jest (NodeJs environment)
      - run: sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --without development --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt-get update; sudo apt-get install postgresql-client-11

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Install JS dependencies
          command: yarn install

      - run:
          name: Javascript tests
          command: yarn test

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Parallel RSpec
          command: bundle exec rspec --order rand


      # Save artifacts
      - store_artifacts:
          path: tmp/screenshots

      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "82:74:4e:8f:30:ea:41:b1:fb:35:0a:85:ce:eb:85:af"

      - deploy:
          name: Deploy QA to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "qa" ]; then
              git push git@heroku.com:technovation-qa.git qa:master
            fi

      - deploy:
          name: Deploy Production to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              git push git@heroku.com:technovation.git production:master
            fi

general:
  branches:
    ignore:
      - /.*-stable/
      - master

deployment:
  beta:
    branch: ra-ui
    heroku:
      appname: tc-2018

  qa:
    branch: qa
    heroku:
      appname: technovation-qa

  prod:
    branch: production
    heroku:
      appname: technovation
