version: 2

jobs:
  build:
    working_directory: ~/technovation-girls
    docker:
      - image: circleci/ruby:2.7.4-bullseye-node-browsers
        auth:
          username: technovationdocker
          password: $DOCKERHUB_PASSWORD
        environment:
          ADMIN_EMAIL: info@technovationchallenge.org
          AIRBRAKE_PROJECT_ID: n-a
          AIRBRAKE_PROJECT_KEY: n-a
          AIRBRAKE_RAILS_ENV: test
          AWS_BUCKET_NAME: technovation-attachments-test
          BING_MAPS_API_KEY: n-a
          CAMPAIGN_MONITOR_API_KEY: n-a
          CHAPTER_AMBASSADOR_SLACK_URL: n-a
          COOKIES_ADMIN_PERMISSION_TOKEN: admin_permission_token_JUNE_2018
          COOKIES_AUTH_TOKEN: auth_token_JUNE_2018
          COOKIES_GLOBAL_INVITATION_TOKEN: global_invitation_token_JUNE_2018
          COOKIES_IP_GEOLOCATION: ip_geolocation_JUNE_2018
          COOKIES_LAST_PROFILE_USED: last_profile_used_JUNE_2018
          COOKIES_LAST_VISITED_SUBMISSION_SECTION: last_visited_submission_section_JUNE_2018
          COOKIES_REDIRECTED_FROM: redirected_from_JUNE_2018
          COOKIES_SESSION_TOKEN: session_token_JUNE_2018
          COOKIES_SIGNUP_EMAIL: n-a
          COOKIES_SIGNUP_TOKEN: signup_token_JUNE_2018
          COOKIES_SIGNUP_WIZARD_MODE: signup_wizard_mode_SEPT_2018
          DATES_CERTIFICATES_AVAILABLE_DAY: 20
          DATES_CERTIFICATES_AVAILABLE_MONTH: 6
          DATES_CERTIFICATES_AVAILABLE_YEAR: 2021
          DATES_DIVISION_CUTOFF_DAY: 1
          DATES_DIVISION_CUTOFF_MONTH: 8
          DATES_DIVISION_CUTOFF_YEAR: 2021
          DATES_LIVE_QUARTERFINALS_ENDS_DAY: 20
          DATES_LIVE_QUARTERFINALS_ENDS_MONTH: 5
          DATES_LIVE_QUARTERFINALS_ENDS_YEAR: 2021
          DATES_MENTOR_TRAINING_DAY: 15
          DATES_MENTOR_TRAINING_MONTH: 10
          DATES_MENTOR_TRAINING_YEAR: 2018
          DATES_NEW_SEASON_START_DAY: 1
          DATES_NEW_SEASON_START_MONTH: 10
          DATES_OFFICIAL_START_OF_SEASON_DAY: 1
          DATES_OFFICIAL_START_OF_SEASON_MONTH: 10
          DATES_OFFICIAL_START_OF_SEASON_YEAR: 2021
          DATES_QUARTERFINALS_BEGINS_DAY: 27
          DATES_QUARTERFINALS_BEGINS_MONTH: 4
          DATES_QUARTERFINALS_BEGINS_YEAR: 2021
          DATES_QUARTERFINALS_ENDS_DAY: 20
          DATES_QUARTERFINALS_ENDS_MONTH: 5
          DATES_QUARTERFINALS_ENDS_YEAR: 2021
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_DAY: 1
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_MONTH: 4
          DATES_REGIONAL_PITCH_EVENTS_BEGINS_YEAR: 2021
          DATES_REGIONAL_PITCH_EVENTS_ENDS_DAY: 1
          DATES_REGIONAL_PITCH_EVENTS_ENDS_MONTH: 5
          DATES_REGIONAL_PITCH_EVENTS_ENDS_YEAR: 2021
          DATES_REGISTRATION_OPENS_DAY: 1
          DATES_REGISTRATION_OPENS_MONTH: 10
          DATES_REGISTRATION_OPENS_YEAR: 2018
          DATES_RPE_OFFICIALITY_FINALIZED_DAY: 22
          DATES_RPE_OFFICIALITY_FINALIZED_MONTH: 4
          DATES_RPE_OFFICIALITY_FINALIZED_YEAR: 2021
          DATES_SEMIFINALS_BEGINS_DAY: 1
          DATES_SEMIFINALS_BEGINS_MONTH: 6
          DATES_SEMIFINALS_BEGINS_YEAR: 2021
          DATES_SEMIFINALS_ENDS_DAY: 17
          DATES_SEMIFINALS_ENDS_MONTH: 6
          DATES_SEMIFINALS_ENDS_YEAR: 2021
          DATES_SUBMISSION_DEADLINE_DAY: 13
          DATES_SUBMISSION_DEADLINE_MONTH: 4
          DATES_SUBMISSION_DEADLINE_YEAR: 2021
          DATES_TEAM_REGISTRATION_DEADLINE_DAY: 16
          DATES_TEAM_REGISTRATION_DEADLINE_MONTH: 3
          DATES_TEAM_REGISTRATION_DEADLINE_YEAR: 2021
          DATES_VIRTUAL_QUARTERFINALS_ENDS_DAY: 20
          DATES_VIRTUAL_QUARTERFINALS_ENDS_MONTH: 5
          DATES_VIRTUAL_QUARTERFINALS_ENDS_YEAR: 2021
          ENABLE_HOMEPAGE_BANNER: true
          FINALISTS_URL: "https://some/url"
          GOOGLE_ANALYTICS_ID: n-a
          GOOGLE_MAPS_API_KEY: n-a
          GOOGLE_PLACES_API_KEY: n-a
          GOOGLE_TIMEZONE_API_KEY: n-a
          HELP_EMAIL: support@technovation.org
          HOST_DOMAIN: localhost:31337
          JUDGE_SLACK_SIGNUP_URL: n-a
          JUDGE_TRAINING_URL: n-a
          MAILCHIMP_API_KEY: n-a
          MAILCHIMP_LIST_ID: n-a
          MAILGUN_PRIVATE_KEY: n-a
          MENTOR_SLACK_SIGNUP_URL: n-a
          NEWSLETTER_URL: "https://some/other/url"
          GENERAL_NEWSLETTER_URL: "https://some/general/url"
          NEW_RELIC_LICENSE_KEY: n-a
          PARENT_CONSENT_PDF: n-a
          PDFTK_PATH: /usr/bin/pdftk
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          REDIS_URL: redis://127.0.0.1:6379/0
          THUNKABLE_PROMO_IMAGE: n-a
          WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
      - image: circleci/postgres:13-ram
        auth:
          username: technovationdocker
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    steps:
      - checkout

      - restore_cache:
          name: Restore cached gems
          keys:
            - v2-gem-cache-{{ checksum "Gemfile.lock" }}
            - v2-gem-cache-

      - restore_cache:
          name: Restore cached node packages
          keys:
            - v1-node-packages-cache-{{ checksum "yarn.lock" }}
            - v1-node-packages-cache-

      - run:
          name: Install PostgreSQL
          command: sudo apt update -y --allow-releaseinfo-change; sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B; sudo apt install postgresql-client-13

      - run:
          name: Install pdftk
          command: sudo apt install pdftk

      - run:
          name: Install wkhtmltopdf
          command: |
            wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
            sudo apt install ./wkhtmltox_0.12.5-1.stretch_amd64.deb

      - run:
          name: Install Jest dependencies
          command: sudo apt install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - run:
          name: Install gems
          command: gem install bundler:2.2.23 && bundle check --path=vendor/bundle || bundle install --without development --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          name: Cache gems
          key: v2-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Install node packages
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          name: Cache node packages
          key: v1-node-packages-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Setup database
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Run Javascript tests
          command: yarn test --maxWorkers=1

      - run:
          name: Run RSpec tests
          command: bundle exec rspec --order rand

      - store_artifacts:
          path: tmp/screenshots

      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "32:c4:d8:7f:60:e0:56:7d:e9:ee:f5:04:e1:9c:2d:4e"

      - deploy:
          name: Deploy QA to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "qa" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/technovation-qa.git qa:master
            fi

      - deploy:
          name: Deploy Production to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/technovation.git qa:master
            fi

general:
  branches:
    ignore:
      - /.*-stable/
      - master

deployment:
  qa:
    branch: qa
    heroku:
      appname: technovation-qa

  prod:
    branch: production
    heroku:
      appname: technovation
