version: 2

jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:latest-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          HELP_EMAIL: help@technovationchallenge.org
          ADMIN_EMAIL: info@technovationchallenge.org
          PDFTK_PATH: /usr/bin/pdftk
          AIRBRAKE_PROJECT_ID: n-a
          AIRBRAKE_PROJECT_KEY: n-a
          NEW_RELIC_LICENSE_KEY: n-a
          GOOGLE_MAPS_API_KEY: n-a
          HOST_DOMAIN: localhost:3000
          AWS_BUCKET_NAME: technovation-attachments-test
          CAMPAIGN_MONITOR_API_KEY: n-a
          STUDENT_LIST_ID: n-a
          MENTOR_LIST_ID: n-a
          JUDGE_LIST_ID: n-a
          REGIONAL_AMBASSADOR_LIST_ID: n-a
          PARENT_LIST_ID: n-a
          REDIS_URL: redis://127.0.0.1:6379/0
          BONSAI_URL: localhost:9200
          GOOGLE_TIMEZONE_API_KEY: n-a
          BING_MAPS_API_KEY: n-a
          SEARCH_INDEX_TIMING: realtime
          RA_SLACK_URL: n-a
          MENTOR_SLACK_SIGNUP_URL: n-a
          STUDENT_SLACK_SIGNUP_URL: n-a
          JUDGE_SLACK_SIGNUP_URL: n-a
          PARENT_CONSENT_PDF: n-a
          JUDGE_TRAINING_URL: n-a
          FINALISTS_URL: "https://some/url"
          NEWSLETTER_URL: "https://some/other/url"
          MAILGUN_PRIVATE_KEY: n-a
          COOKIES_ADMIN_PERMISSION_TOKEN: admin_permission_token_JUNE_2018
          COOKIES_AUTH_TOKEN: auth_token_JUNE_2018
          COOKIES_GLOBAL_INVITATION_TOKEN: global_invitation_token_JUNE_2018
          COOKIES_LAST_PROFILE_USED: last_profile_used_JUNE_2018
          COOKIES_LAST_VISITED_SUBMISSION_SECTION: last_visited_submission_section_JUNE_2018
          COOKIES_IP_GEOLOCATION: ip_geolocation_JUNE_2018
          COOKIES_REDIRECTED_FROM: redirected_from_JUNE_2018
          COOKIES_SIGNUP_TOKEN: signup_token_JUNE_2018
          COOKIES_SESSION_TOKEN: session_token_JUNE_2018
      - image: circleci/postgres:9.6-alpine-ram

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run: sudo apt-get update; sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x

      - run: sudo apt-get install pdftk

      - run: sudo apt-get install yarn

      # Needed to polyfill canvas elements for testing in Jest (NodeJs environment)
      - run: sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt-get update; sudo apt-get install postgresql-client-10

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Install JS dependencies
          command: yarn install

      - run:
          name: Javascript tests
          command: yarn test

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Parallel RSpec
          command: bundle exec rspec --order rand


      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "82:74:4e:8f:30:ea:41:b1:fb:35:0a:85:ce:eb:85:af"

      - deploy:
          name: Deploy QA to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "qa" ]; then
              git push git@heroku.com:technovation-qa.git qa:master
            fi

      - deploy:
          name: Deploy Production to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              git push git@heroku.com:technovation.git production:master
            fi

general:
  branches:
    ignore:
      - /.*-stable/
      - master

deployment:
  beta:
    branch: ra-ui
    heroku:
      appname: tc-2018

  qa:
    branch: qa
    heroku:
      appname: technovation-qa

  prod:
    branch: production
    heroku:
      appname: technovation
