version: '3.0'
services:
  app:
    build: .
    volumes:
      - .:/var/app
      - app-bundle:/bundle
    command: sh -c 'bundle install && bin/rails server --port 3000 --binding 0.0.0.0'
    links:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9009:9009"
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: [ "redis-server" ]

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: technovation-app_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true
  
volumes:
  pgdata:
  app-bundle: {}

