---
page_width: 792.0
page_height: 612.0
fields:
  RecipientName 5:
    x: 81.0
    "y": 244.8
    width: 630.0
    height: 25.8
    align: left
    size: 12
    color: "#000000"
    font_style: normal
  Text Field 13:
    x: 122.0
    "y": 171.8
    width: 546.9
    height: 58.3
    align: left
    size: 12
    color: "#000000"
    font_style: normal
