---
page_width: 792.0
page_height: 612.0
fields:
  VolunteerDescription:
    x: 445.1
    "y": 215.6
    width: 277.8
    height: 112.9
    align: left
    size: 12
    color: "#000000"
    font_style: normal
  Recipient:
    x: 445.1
    "y": 337.9
    width: 394.6
    height: 25.8
    align: left
    size: 12
    color: "#000000"
    font_style: bold
