---
page_width: 792.0
page_height: 612.0
fields:
  RecipientName 3:
    x: 81.0
    "y": 285.5
    width: 630.0
    height: 25.8
    align: left
    size: 12
    color: "#000000"
    font_style: normal
  Text Field 11:
    x: 122.0
    "y": 164.8
    width: 546.9
    height: 95.2
    align: left
    size: 12
    color: "#000000"
    font_style: normal
