language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx

gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile

matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
