module ConsentForms
  PAPER_CONSENT_UPLOAD_STATUSES = {
    pending: 0,
    approved: 1,
    rejected: 2
  }

  PARENT_GUARDIAN_NAME_FOR_A_PAPER_CONSENT = "ON FILE"
  PARENT_GUARDIAN_EMAIL_ADDDRESS_FOR_A_PAPER_CONSENT = "ON FILE"
  ELECTRONIC_SIGNATURE_FOR_A_PAPER_CONSENT = "ON FILE"

  FIRST_SEASON_FOR_UPLOADABLE_CONSENT_FORMS = 2024
end
