---
page_width: 792.0
page_height: 612.0
fields:
  full_name:
    x: 84.7
    "y": 245.6
    width: 659.7
    height: 47.3
    align: left
    size: 18
    color: "#041e42"
    font_style: normal
  full_text:
    x: 84.7
    "y": 160.5
    width: 387.1
    height: 63.3
    align: left
    size: 14
    color: "#041e42"
    font_style: bold
