---
page_width: 792.0
page_height: 612.0
fields:
  Recipient Name:
    x: 119.6
    "y": 247.3
    width: 553.2
    height: 24.6
    align: left
    size: 18
    color: "#252526"
    font_style: normal
  description 1:
    x: 119.6
    "y": 180.7
    width: 553.2
    height: 24.6
    align: left
    size: 15
    color: "#252526"
    font_style: normal
  description 2:
    x: 119.6
    "y": 143.6
    width: 553.2
    height: 24.6
    align: left
    size: 15
    color: "#252526"
    font_style: normal
