language: ruby

sudo: false

rvm:
  - 2.1
  - 2.0
  - 1.9

env:
  - RAILS=master DB=sqlite3
  - RAILS=master DB=mysql
  - RAILS=master DB=postgres
  - RAILS=4-1-stable DB=sqlite3
  - RAILS=4-1-stable DB=mysql
  - RAILS=4-1-stable DB=postgres
  - RAILS=4-0-stable DB=sqlite3
  - RAILS=4-0-stable DB=mysql
  - RAILS=4-0-stable DB=postgres
  - RAILS=3-2-stable DB=sqlite
  - RAILS=3-2-stable DB=mysql
  - RAILS=3-2-stable DB=postgres
  - RAILS=3-1-stable DB=sqlite
  - RAILS=3-1-stable DB=mysql
  - RAILS=3-1-stable DB=postgres
  - RAILS=3-0-stable DB=sqlite
  - RAILS=3-0-stable DB=mysql
  - RAILS=3-0-stable DB=postgres

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
