---
page_width: 792.0
page_height: 612.0
fields:
  full_name:
    x: 86.6
    "y": 299.0
    width: 643.6
    height: 28.6
    align: left
    size: 18
    color: "#ffffff"
    font_style: normal
  full_text:
    x: 86.6
    "y": 211.3
    width: 556.9
    height: 83.3
    align: left
    size: 14
    color: "#ffffff"
    font_style: bold
